if(EXISTS "C:/Users/aless/Desktop/PCS2023_Exercises-main/Projects/build-Delaunay-Desktop-Debug/delaunay_test[1]_tests.cmake")
  include("C:/Users/aless/Desktop/PCS2023_Exercises-main/Projects/build-Delaunay-Desktop-Debug/delaunay_test[1]_tests.cmake")
else()
  add_test(delaunay_test_NOT_BUILT delaunay_test_NOT_BUILT)
endif()
